webtalk_init -webtalk_dir C:/Users/evanm/Documents/ESIREM/4a/S7/FPGA/Projet_TP/Projet_TP.sim/sim_1/behav/xsim/xsim.dir/Mem_Cache_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 11 13:45:03 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dadc57d4-84f2-4ac4-81d6-11b3b1a03ee3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "07016c82186649a19da4fb647dbeb17d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "233" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "252525 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18656_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2535983376 -regid "" -xml C:/Users/evanm/Documents/ESIREM/4a/S7/FPGA/Projet_TP/Projet_TP.sim/sim_1/behav/xsim/xsim.dir/Mem_Cache_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/evanm/Documents/ESIREM/4a/S7/FPGA/Projet_TP/Projet_TP.sim/sim_1/behav/xsim/xsim.dir/Mem_Cache_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/evanm/Documents/ESIREM/4a/S7/FPGA/Projet_TP/Projet_TP.sim/sim_1/behav/xsim/xsim.dir/Mem_Cache_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
